# Generated by Django 4.2.1 on 2023-06-18 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Profile',
        ),
    ]
