# Generated by Django 4.2.1 on 2023-06-01 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(default='default', max_length=80)),
                ('rate_schedule', models.CharField(default='default', max_length=80)),
                ('distributor_id', models.CharField(default='default', max_length=80)),
                ('selected_offer_id', models.CharField(default='default', max_length=80)),
                ('user_id', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
