# Generated by Django 4.2.1 on 2023-06-02 02:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("MainApplication", "0002_userprofile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserProfile",
            new_name="CustomUser",
        ),
    ]
