# Generated by Django 4.2.1 on 2023-06-02 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApplication', '0004_rename_customuser_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
