# Generated by Django 4.2.1 on 2023-06-02 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainApplication', '0005_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_preferences',
            name='user_id',
            field=models.OneToOneField(default='default', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
