# Generated by Django 4.1.1 on 2023-06-03 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("MainApplication", "0007_user_preferences_selected_offer_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_preferences",
            name="distributor_id",
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name="user_preferences",
            name="rate_schedule",
            field=models.CharField(default="default", max_length=80),
        ),
        migrations.AlterField(
            model_name="user_preferences",
            name="selected_offer_id",
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name="user_preferences",
            name="selected_offer_rate",
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name="user_preferences",
            name="user_id",
            field=models.ForeignKey(
                default="default",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user_preferences",
            name="zip_code",
            field=models.CharField(default="default", max_length=10),
        ),
    ]
