# Generated by Django 4.2.1 on 2023-06-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenEnergySearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_preferences',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
