# Generated by Django 4.1.1 on 2023-07-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GreenEnergySearch", "0002_user_preferences_email_notifications"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_preferences",
            name="selected_offer_id",
        ),
        migrations.RemoveField(
            model_name="user_preferences",
            name="selected_offer_rate",
        ),
        migrations.AddField(
            model_name="user_preferences",
            name="selected_offer",
            field=models.JSONField(default={}),
        ),
    ]
