# Generated by Django 4.1.1 on 2023-07-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "GreenEnergySearch",
            "0003_remove_user_preferences_selected_offer_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_preferences",
            name="selected_offer",
            field=models.JSONField(default=dict),
        ),
    ]
