# Generated by Django 4.1.1 on 2023-07-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GreenEnergySearch", "0004_alter_user_preferences_selected_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_preferences",
            name="test",
            field=models.JSONField(default=list),
        ),
    ]
