# Generated by Django 4.1.1 on 2023-07-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GreenEnergySearch", "0005_user_preferences_test"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_preferences",
            name="test",
        ),
        migrations.AddField(
            model_name="user_preferences",
            name="possible_selections",
            field=models.JSONField(default=list),
        ),
    ]
