# Generated by Django 4.1.1 on 2023-07-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('GreenEnergySearch', '0006_remove_user_preferences_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_preferences',
            name='possible_selections',
            model_name="user_preferences",
            name="possible_selections",
            field=models.JSONField(default=list),
        ),
    ]
