# Generated by Django 4.2.3 on 2023-07-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenEnergySearch', '0007_alter_user_preferences_possible_selections')
    ]

    operations = [
        migrations.AlterField(
            model_name='user_preferences',
            name='possible_selections',
            field=models.JSONField(default={"last_updated": None, "offers": []}),
        ),
    ]
