# Generated by Django 4.1.1 on 2023-07-22 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GreenEnergySearch", "0007_alter_user_preferences_possible_selections"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_preferences",
            name="selected_offer_expected_end",
            field=models.DateField(default=datetime.date(2023, 7, 22)),
        ),
        migrations.AddField(
            model_name="user_preferences",
            name="selected_offer_selected_date",
            field=models.DateField(default=datetime.date(2023, 7, 22)),
        ),
        migrations.AlterField(
            model_name="user_preferences",
            name="possible_selections",
            field=models.JSONField(default={"last_updated": None, "offers": []}),
        ),
    ]
