# Generated by Django 4.1.1 on 2023-07-23 03:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "GreenEnergySearch",
            "0009_alter_user_preferences_selected_offer_expected_end_and_more",
        ),
        ("GreenEnergySearch", "0010_alter_user_preferences_possible_selections"),
    ]

    operations = []
