# Generated by Django 4.2.3 on 2023-07-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GreenEnergySearch", "0011_merge_20230722_2119"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_preferences",
            name="distributor_name",
            field=models.CharField(default="", max_length=80),
        ),
    ]
